apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: srmt-documind
  labels:
    app: srmt-documind
spec:
  output:
    to:
      kind: ImageStreamTag
      name: srmt-documind:latest
  source:
    type: Git
    git:
      uri: https://github.com/goumack/ALEX-Assistant-IA.git
      ref: main
    contextDir: .
  strategy:
    type: Docker
    dockerStrategy:
      dockerfilePath: Dockerfile
  triggers:
  - type: ConfigChange
  - type: ImageChange
